# fly.toml app configuration file generated for emailsearch on 2025-02-24T16:54:04-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emailsearch'
primary_region = 'sjc'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
